from __future__ import annotations

import typing as t

import numpy as np
import numpy.typing as npt


Scalar = int | float | complex | np.integer | np.floating | np.complexfloating


class NBitState[N](npt.NDArray[np.complexfloating]):
    def __add__(self, other: NBitState[N]) -> t.Self: ...
    def __sub__(self, other: NBitState[N]) -> t.Self: ...
    def __mul__(self, other: Scalar) -> t.Self: ...
    def __truediv__(self, scalar: Scalar) -> t.Self: ...


class NBitOperation[N](npt.NDArray[np.complexfloating]):
    def __add__(self, other: NBitOperation[N]) -> t.Self: ...
    def __sub__(self, other: NBitOperation[N]) -> t.Self: ...
    def __truediv__(self, scalar: Scalar) -> t.Self: ...
    @t.overload
    def __matmul__(self, other: NBitOperation[N]) -> t.Self: ...
    @t.overload
    def __matmul__(self, other: NBitState[N]) -> NBitState[N]: ...
